### ISSUE TITLE
Twig Runtime Error when Neo isn't installed

### ISSUE THREAD

**Issue by jwb009** [simplygoodwork/craft-block-usage#1]
Thanks for the plugin, I've wanted something like this for awhile!

I'm encountering a Twig Runtime Error when clicking on the Block Name field: 

`Calling unknown method: craft\web\twig\variables\CraftVariable::neo()`

I'm guessing this is because I don't have Neo.

**Comment by RyanRoberts** [comment]
+1

**Comment by chrisrowe** [comment]
Eeek, sorry about this, a little bit of old code got left behind. This is now resolved in 1.0.1
