### ISSUE TITLE
Error on Neoblocks

### ISSUE THREAD

**Issue by LinneaHarts** [simplygoodwork/craft-block-usage#2]
I'm getting an error when viewing Neo Blocks on a Neo field where the blocks are nested 3 deep (at least I think that's the problem)

TypeError
simplygoodwork\blockusage\services\BlockUsageService::_getNeoChildBlocks(): Argument #1 ($fieldHandle) must be of type string, array given, called in /mnt/www/skillsoft.com/adhoc/vendor/simplygoodwork/craft-block-usage/src/services/BlockUsageService.php on line 142

Using Craft 4.4.8 currently, and the latest Block Usage

**Comment by chrisrowe** [comment]
Thanks for the PR, I have just merged that today!
