### ISSUE TITLE
Recursive Neo blocks support?

### ISSUE THREAD

**Issue by danieltott** [simplygoodwork/craft-block-usage#5]
Hey y'all! This is a great idea for a plugin - thanks for the work!

I've run in to an issue however - our neo field supports recursive blocks, and I believe that is freezing up this plugin. 

My recursive blocks I mean something like I have a `Container` block type, whose children can also be `Container`.

This freezes `craft-block-usage` entirely.

I'm not sure what the best solution would be - maybe loading block types per level?

**Comment by chrisrowe** [comment]
Hey, ha yeah that's pretty weird edge case. We can take a look at this but we'll probably need a more substantial rewrite for C5 support anyway.

**Comment by danieltott** [comment]
I'm not sure I agree it's a weird edge case - but either way, I filed a PR #7 that will fix up this issue and another issue I found 😁

**Comment by proimage** [comment]
I'll second this; we use Neo's block nesting heavily in nearly every major Neo field we create. `Container` with various "content" blocks, `Tabs` with `Tab` children and "content" grandchildren, etc.
